run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "unchecked error"

